version: '3.3'

services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=messaggio
      - POSTGRES_PASSWORD=messaggio
      - DB_NAME=postgres
      - DB_SSLMODE=disable
    ports:
      - "5437:5432"
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9093"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    networks:
      - app-network


  messaggio:
    build: .
    depends_on:
      - kafka
      - postgres
    environment:
      - .env
    ports:
      - "8071:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
